spring.application.name=SpringBootDemo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://localhost:5432/pgadatabase
spring.datasource.username=pguser
spring.datasource.password=pgpassword

