spring.application.name=SpringBootDemo
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://localhost:5432/pgdatabase
spring.datasource.username=pguser
spring.datasource.password=pgpassword

